// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20230331161555_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            Age = 7,
                            Breed = "Siamese",
                            Name = "Jeremy"
                        },
                        new
                        {
                            CatId = 2,
                            Age = 4,
                            Breed = "Sphynx",
                            Name = "Matilda"
                        },
                        new
                        {
                            CatId = 3,
                            Age = 9,
                            Breed = "Persian",
                            Name = "Sarah"
                        },
                        new
                        {
                            CatId = 4,
                            Age = 3,
                            Breed = "Burmese",
                            Name = "Jake"
                        },
                        new
                        {
                            CatId = 5,
                            Age = 2,
                            Breed = "Siberian",
                            Name = "Bartholomeow"
                        });
                });

            modelBuilder.Entity("AnimalShelterApi.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Age = 2,
                            Breed = "Golden Retriever",
                            Name = "Garfield"
                        },
                        new
                        {
                            DogId = 2,
                            Age = 5,
                            Breed = "Bulldog",
                            Name = "Bazinga"
                        },
                        new
                        {
                            DogId = 3,
                            Age = 8,
                            Breed = "Poodle",
                            Name = "Rigby"
                        },
                        new
                        {
                            DogId = 4,
                            Age = 1,
                            Breed = "German Sheperd",
                            Name = "Clarence"
                        },
                        new
                        {
                            DogId = 5,
                            Age = 6,
                            Breed = "Border Collie",
                            Name = "Stitch"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
